# Generated by Django 6.1 on 2026-09-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_coordinador_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='numero_legajo',
            field=models.IntegerField(),
        ),
    ]
