# Generated by Django 6.1 on 2026-09-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_empleado_numero_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='numero_documento',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_legajo',
            field=models.IntegerField(unique=True),
        ),
    ]
