# Generated by Django 6.1 on 2026-09-03 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_coordinador_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_servicio', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.coordinador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
    ]
